# Generated by Django 5.1 on 2024-08-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_image_url_recipe_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('recipe', 'added_at')},
        ),
    ]
