# Generated by Django 5.1 on 2024-08-28 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('recipe',)},
        ),
    ]
